# Generated by Django 3.1.7 on 2021-03-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlist',
            name='icon',
            field=models.CharField(choices=[('Included', 'bi bi-check-square'), ('Not included', 'bi bi-x-square')], max_length=40),
        ),
    ]
