# Generated by Django 3.1.7 on 2021-03-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0005_auto_20210311_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlist',
            name='icon',
            field=models.CharField(choices=[('bi bi-check2', 'Included'), ('bi bi-x-square', 'Not included')], max_length=40),
        ),
    ]
